"""
Traction Distribution Connector (TDMS data)
----------------------------------------------
Reads data/synthetic/synthetic_TDMS_traction_defects.csv and loads
it into raw_defect_ingest. Real data generated by Person 1 — not
independently synthesized here.

Source columns (verified against the actual file) — note this file
uses `requires_power_block` where TMS/SMMS use `requires_traffic_block`;
both map to the same requires_block column here:
    tdms_record_id, corridor_id, from_station, to_station, zone,
    defect_type, severity_class, detected_date, originally_due_date,
    days_overdue, requires_power_block, estimated_repair_duration_hrs,
    department

CSV_PATH below points at the reference copy used to build/test this
connector. In the real repo, update it to the actual path:
    data/synthetic/synthetic_TDMS_traction_defects.csv
"""

import sqlite3
import csv
import json
import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "db", "railway.db")
CSV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "data", "synthetic", "synthetic_TDMS_traction_defects.csv")
DEPARTMENT = "Traction Distribution"


def load_records(csv_path=CSV_PATH):
    records = []
    with open(csv_path, newline="") as f:
        for row in csv.DictReader(f):
            records.append(row)
    return records


def insert_records(records, conn):
    cur = conn.cursor()
    for r in records:
        cur.execute(
            """
            INSERT INTO raw_defect_ingest
                (department, source_record_id, corridor_id, zone, defect_type, severity_class,
                 days_overdue, estimated_repair_duration_hrs, requires_block, raw_payload)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                DEPARTMENT,
                r["tdms_record_id"],
                r["corridor_id"],
                r["zone"],
                r["defect_type"],
                r["severity_class"],
                int(r["days_overdue"]),
                float(r["estimated_repair_duration_hrs"]),
                1 if r["requires_power_block"].strip().lower() == "true" else 0,
                json.dumps(r),
            ),
        )
    conn.commit()
    return cur.rowcount


def run(csv_path=CSV_PATH, db_path=DB_PATH):
    conn = sqlite3.connect(db_path)
    records = load_records(csv_path)
    insert_records(records, conn)
    print(f"[Traction Distribution connector] Loaded {len(records)} records from {os.path.basename(csv_path)}.")
    conn.close()


if __name__ == "__main__":
    run()
